// This file is generated by Sapper — do not edit it!
import root from '../../routes/_layout.html';
import error from '../../routes/_error.html';

const index = () =>
	import(/* webpackChunkName: "index" */ '../../routes/index.html');
const examples_$slug = () =>
	import(/* webpackChunkName: "examples_$slug" */ '../../routes/examples/[slug].html');
const guide = () =>
	import(/* webpackChunkName: "guide" */ '../../routes/guide/index.html');
const test = () =>
	import(/* webpackChunkName: "test" */ '../../routes/test.html');

export const manifest = {
	ignore: [/^\/examples\/([^\/]+?).json\/?$/, /^\/api\/guide\/?$/, /^\/api\/guide\/contents\/?$/],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		},

		{
			// examples/[slug].html
			pattern: /^\/examples\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: examples_$slug, params: match => ({ slug: match[1] }) }
			]
		},

		{
			// guide/index.html
			pattern: /^\/guide\/?$/,
			parts: [
				null,
				{ component: guide }
			]
		},

		{
			// test.html
			pattern: /^\/test\/?$/,
			parts: [
				{ component: test }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};

if (module.hot) {
	import('/Users/mhk/wrk/code/layercake.graphics/node_modules/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}