// This file is generated by Sapper — do not edit it!
export const timestamp = 1539829474527;

export const assets = [
	"CNAME",
	"copy.svg",
	"deps.json",
	"global.css",
	"hljs.css",
	"icons/download.svg",
	"layercake-logo-100.png",
	"layercake-logo-1200.png",
	"layercake-logo-128.png",
	"layercake-logo-192.png",
	"layercake-logo-500x400.png",
	"layercake-logo-512.png",
	"manifest.json",
	"svelte-app.json"
];

export const shell = [
	"client/879d6f4b3bf2d029b570/examples_$slug.examples_$slug.js",
	"client/879d6f4b3bf2d029b570/guide.guide.js",
	"client/879d6f4b3bf2d029b570/index.index.js",
	"client/879d6f4b3bf2d029b570/main.js",
	"client/879d6f4b3bf2d029b570/test.test.js",
	"client/879d6f4b3bf2d029b570/0.0.js",
	"client/879d6f4b3bf2d029b570/vendors~examples_$slug.vendors~examples_$slug.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/examples\/([^\/]+?)\/?$/ },
	{ pattern: /^\/guide\/?$/ },
	{ pattern: /^\/test\/?$/ }
];